version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: sdmwHwCsiPooY
      MYSQL_DATABASE: mywebsite
      MYSQL_USER: burakyapici
      MYSQL_PASSWORD: Bfp711g+
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
