package com.blog.mywebsite.validation;

import jakarta.annotation.Generated;

@Generated(
        value = "org.mapstruct.ap.MappingProcessor",
        date = "2024-07-01T00:00:00+0000",
        comments = "Generated by MapStruct"
)
public @interface CustomGenerated {
}
